problem: "x**3 * exp(-x) * cos(x) * sin(x) * (sin(x)**2 * cos(x) - 1)"  # Example
train_range:
  min: 0.0
  max: 0.2
  step: 0.004
test_range:
  min: 0.05
  max: 0.05
  step: 0.001
function_set: ["+", "-", "*", "/"]
terminal_set: ["x", "y"]
constant_range:
  min: -5
  max: 5
  count: 50
